name: Template
version: '${project.version}'
main: me.kruase.kotlinplugintemplate.Template
api-version: 1.16
authors: [ KruASe ]

description: Template project for kotlin spigot plugins

libraries:
    - org.jetbrains.kotlin:kotlin-stdlib:1.7.10

commands:
    template:
        description: Main Template plugin command
        permission: template.help
        usage: |-
            §7Run §6/help <command> [n] §7to get page n of help
            §a/<command> help [command] §r- Show help for given command, for available commands otherwise
        aliases:
            - tmp

permissions:
    template.help:
        description: Allows to use §a/tmp help §r(lists only available commands)
        default: true
    template.reload:
        description: Allows to use §a/tmp reload
        default: op
    template.admin:
        description: Refers to §template.reload §rby default
        default: op
        children:
            template.reload: true
